// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qeppulkekdbrmvriqioq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlcHB1bGtla2Ricm12cmlxaW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzE5NTQsImV4cCI6MjA2MDgwNzk1NH0.x6tWDdaJRn8NIumqBUhH0zLv_03Ccq1-zZpwzRkYKMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);